name: Global compiler test

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Global compiler test
      run: make compiler_test-CI
