name: Dynamic array test

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make array_test 
      run: make array_test-CI
