name: Dynamic String Test

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Dynamic String Test
      run: make string_test-CI
