name: Lexer Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: Lexer test
      run: make ltest 
    - name: Symtab test
      run: make stest 
    - name: Parser test
      run: make ptest 
